# hx3d toolkit config
#####################

# Debug mode
debug_mode: True

# Compiler and debugger
cxx_compiler: clang++
debugger: gdb

# Android configuration
android_toolchain: /opt/custom-ndk
android_build_type: Debug

# Browser
web_browser: xdg-open

# Providers
providers:
  audio: SDL2
  window: SDL2

# Generator
generator:
  framework:
    repository: https://github.com/Srynetix/hx3d-framework.git
    branch: new_gen
  tools:
    repository: https://github.com/Srynetix/hx3d-tools.git
    branch: master

# Memcheck configuration
memcheck:
  tool: valgrind --leak-check=full --suppressions=../../tools/toolkit/valgrind.supp
